# Dockerfile.p1
FROM php:8.1-fpm
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
RUN apt update && apt install -y zip git libicu-dev locales
RUN docker-php-ext-install opcache intl pdo_mysql
RUN locale-gen fr_FR.UTF-8
WORKDIR /var/www/diablo4Blog/html
#COPY ./html/composer.json .
#RUN composer install
#COPY ./html .
RUN usermod -u 1000 www-data